version: '3.9'
services:
  wsgi:
    build: .
    environment:
      APP_LOG_FILE: ./logs/app.log
      APP_LOG_FILE_BACKUP_COUNT: 2
      APP_LOG_FILE_ENCODING: UTF-8
      APP_LOG_FILE_MAX_BYTES: 1024
    ports:
      - '8000:8000'
    volumes:
      - .:/app

  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
